Git homework
denzelz/common pull request #1
Opened 2019-09-26 07:43 UTC by denzelz

2019-09-27 13:52 UTC, dimigor requested changes

2019-09-27 13:52 UTC, dimigor commented on git/homework.py
> +    return True if first == second else False
you do not need this check, operators like `is, in, ==` already return bool value

2019-09-27 13:52 UTC, dimigor commented on git/homework.py
> +    return True if id(first) == id(second) else False
Take a look at `is`

2019-09-28 10:18 UTC, yuriimchg requested changes
перевірив ще раз, завдання виглядають дуже класно :+1: 
є ще зауваження до стилізації: 

homework.py:25:1: E303 too many blank lines (4)
homework.py:33:1: E302 expected 2 blank lines, found 1
homework.py:41:1: E302 expected 2 blank lines, found 1
homework.py:61:1: E302 expected 2 blank lines, found 1
homework.py:114:1: E302 expected 2 blank lines, found 1
homework.py:119:47: E231 missing whitespace after ','
homework.py:132:33: E225 missing whitespace around operator
homework.py:134:1: E302 expected 2 blank lines, found 1
homework.py:157:10: E225 missing whitespace around operator
homework.py:164:16: W292 no newline at end of file

На майбутнє їх можна побачити за допомогою `flake8`.
Трошки більше про стандарти стилізації в Python: https://www.python.org/dev/peps/pep-0008/

2019-09-28 11:54 UTC, yuriimchg approved these changes
все гуд :+1: 
молодець :+1: 
на майбутнє ще глянь завдання, які я виправив
їх також можна без зайвих if / else

2019-09-28 11:54 UTC, yuriimchg commented on git/homework.py
> +    return True if type(first) == type(second) else False
```suggestion
    return type(first) == type(second) 
```

2019-09-28 11:54 UTC, yuriimchg commented on git/homework.py
> +    return True if first is second else False
```suggestion
    return first is second 
```

2019-09-28 12:09 UTC, merged